### ISSUE TITLE
Cannot read any 64-bit values

### ISSUE THREAD

**Issue by cdhowie** [dobesv/node-binstruct#4] opened 2017-02-20 17:19 UTC
There appears to be a bug on line 282 of `binstruct.js` where required parameters `def` and `field` are not passed to the reader implementation, resulting in this exception:

```
Fatal TypeError: Cannot read property 'int64mode' of undefined
    at Buffer.readInt64AsNumber (/home/chris/dev/cia-serve/node_modules/binstruct/binstruct.js:101:24)
    at readField (/home/chris/dev/cia-serve/node_modules/binstruct/binstruct.js:282:28)
    at Array.forEach (native)
    at StructDef.readFieldsFromBuf (/home/chris/dev/cia-serve/node_modules/binstruct/binstruct.js:279:14)
```

**Comment by dobesv** [comment] 2017-02-20 18:32
Yes, you are right.  I have pushed a fix, please try it out.

**Comment by dobesv** [comment] 2017-02-20 18:32
If the issue is fixed please close this issue!

**Closed** 2017-12-13 18:05 UTC

**Comment by cdhowie** [comment] 2017-12-15 17:37
@dobesv Just saw this today, my apologies for not closing the issue in February.  Yes, it is fixed.
